import './globals.scss'
import { League_Spartan } from 'next/font/google';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const spartan = League_Spartan({
  weight: ["700"],
  subsets: ["latin"],
  variable: '--font-spartan'
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        
        <nav className={spartan.variable}>

          <img
            className="logo"
            src="https://user-images.githubusercontent.com/73386100/231491201-77f9d1d4-ead5-434f-9959-bb07b9bf0369.png"
            alt="Logo">
          </img>

          <ul>
            <li>Case Studies</li>
            <li>Experiments</li>
            <li>Contanct</li>
            <li>
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                <path
                  d="M448 256c0-106-86-192-192-192V448c106 0 192-86 192-192zm64 0c0 141.4-114.6 256-256 256S0 397.4 0 256S114.6 0 256 0S512 114.6 512 256z" />
              </svg>
            </li>
          </ul>

          <span onclick="toggle()">
            <div style={{ width: 45 }} />
            <div style={{ width: 35, transform: "translate(10px)" }} />
            <div style={{ width: 25, transform: "translate(20px)" }} />
          </span>

        </nav>

        {children}

      </body>
    </html>
  )
}
